### ISSUE TITLE
MaxDOP_Configuration_Check.sql gives me an incorrect result

### ISSUE THREAD

**Issue by acappelletti** [MadeiraData/MadeiraToolbox#11]
Hi
I try some run on different server and found that the result isn't correct.

I got: 
@@SERVERNAME: MSSQL01
@EffectiveMaxDOP: 2 (YES TRUE)
@NumaNodeCount: 1 (NO I GOT 2 NUMA... see the image)

SELECT * FROM sys.dm_os_nodes	
![image](https://github.com/MadeiraData/MadeiraToolbox/assets/43847440/da72d401-8e15-408a-baae-93f581a0ce22)

but from SSMS I got a single one?
![image](https://github.com/MadeiraData/MadeiraToolbox/assets/43847440/eb4422ba-3796-4e18-8298-921dcf705687)

Which is the correct?
I see you count distinct on this...
![image](https://github.com/MadeiraData/MadeiraToolbox/assets/43847440/9dda34d1-b0fc-4a27-9677-8bf07a88e49d)

And also from server log:

- SQL Server detected 4 sockets with 4 cores per socket and 4 logical processors per socket, 16 total logical processors; using 16 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
-  Automatic soft-NUMA was enabled because SQL Server has detected hardware NUMA nodes with greater than 8 physical cores.

@LogicalProcessorPerNumaNodeCount: 16 (NO ARE 8... see the above)
--------
MaxDOP is already within recommended range: 8 (NO IT's 2)

I'm little confused,
Thanks Alen

**Comment by EitanBlumin** [comment]
Hi @acappelletti , thank you for your submission.

Please note that the calculation is NOT done per `node_id`, but it's done per `memory_node_id`. That's the one that matters.

That's also why in SSMS you get a single NumaNode0 in the processor tab. You only have one in your case.

**Comment by acappelletti** [comment]
Thank you very much @EitanBlumin for clarify me...
so having found the servers with MAX degree at 2 the limit is conceivable anyway up to 8... initially my doubt was up to 4 (numbers of CPUs x sockets) but now what matters are the soft-NUMAs as per the MS documentation , correct?

In fact, I tried to test a HINT on an analytical query from 2 to 4-8-16 (using them all) obtaining a strong reduction in time (1'45" to 35").

But "memory_node_id" is the physical memory slot? For this reason what do you say is what matters?
Thanks, ALEN

**Comment by EitanBlumin** [comment]
Yes, @acappelletti , that's correct.

The "memory_node_id" is the physical memory slot which is what matters.
