### ISSUE TITLE
Add missing checks to the Condensed BP Check script

### ISSUE THREAD

**Issue by EitanBlumin** [MadeiraData/MadeiraToolbox#2]
We have a "condensed check" script of best practices that we're usually using for the SQL Server Review:

https://github.com/MadeiraData/MadeiraToolbox/blob/8f478c3166d8e3f0284bbea12a69f33afda7716d/Best%20Practices%20Checklists/Best%20Practices%20Condensed%20Check.sql

However, it's incomplete, and missing several checks, most of which exist in other scripts:

- [ ] [High VLF Count](https://github.com/MadeiraData/MadeiraToolbox/blob/master/Best%20Practices%20Checklists/High_VLF_Count_Multiversion.sql)
- [ ] [Foreign Keys without corresponding indexes](https://github.com/MadeiraData/MadeiraToolbox/blob/master/Best%20Practices%20Checklists/Foreign_Keys_Without_Corresponding_Indexes.sql)
- [ ] [Heap Tables](https://github.com/MadeiraData/MadeiraToolbox/blob/master/Best%20Practices%20Checklists/Heap_Tables.sql)
- [ ] [Invalid owner for system schema role or database](https://github.com/MadeiraData/MadeiraToolbox/blob/master/Best%20Practices%20Checklists/Invalid_owner_for_system_schema_role_or_database.sql)
- [ ] [Outdated Statistics](https://github.com/MadeiraData/MadeiraToolbox/blob/master/Best%20Practices%20Checklists/Outdated_Statistics.sql)
- [ ] [Redundant Indexes](https://gist.github.com/EitanBlumin/c9b4336ed89daf22cd406c9ce974f023)
- [ ] [Orphaned jobs](https://github.com/MadeiraData/MadeiraToolbox/blob/master/Best%20Practices%20Checklists/Orphaned%20SQL%20Agent%20Jobs.sql)
- [ ] [Additional checks from Azure-SQL-Tips](https://github.com/microsoft/azure-sql-tips/wiki/Azure-SQL-Database-tips)
- [ ] [Table and Index High Unused Space](https://github.com/MadeiraData/MadeiraToolbox/blob/master/Health%20Check%20Scripts/Table%20and%20Index%20High%20Unused%20Space.sql)

Feel free to also add more checks and list them here.

**Comment by Tovli** [comment]
I've also opened an issue to make it suitable for AzureSql #5

**Comment by EitanBlumin** [comment]
This issue was duplicated into our new repository: https://github.com/MadeiraData/microsoft-dbas-club/issues/1
