### ISSUE TITLE
Best practices not suitable for Azure SQL

### ISSUE THREAD

**Issue by Tovli** [MadeiraData/MadeiraToolbox#5]
Hi,
Is there any plan (or other script) that can check best practices for Azure SQL?
I've tried using [this](https://github.com/MadeiraData/MadeiraToolbox/blob/078d5ecf3d86bce9f721d19f6e3cc4e81a6711e0/Best%20Practices%20Checklists/Best%20Practices%20Condensed%20Check.sql) but it failed as AzureSql doesn't have msdb access

**Comment by EitanBlumin** [comment]
Hi Dekel,

We don't have a condensed script of best practice checks suitable for Azure SQL, but there actually is one developed by Microsoft, available here:

https://github.com/microsoft/azure-sql-tips

**Comment by Tovli** [comment]
Thanks @EitanBlumin 
That's a great start although your scripts are much more informative :)

**Comment by EitanBlumin** [comment]
This issue was duplicated into our new repository: https://github.com/MadeiraData/microsoft-dbas-club/issues/2
